### ISSUE TITLE
PHP - Additional zend_extension lines get rewritten to xdebug

### ISSUE THREAD

**Issue by billyrud** [easyphp/DEVSERVER#105]
Any additional zend_extension lines in php.ini get rewritten to xdebug when the http server starts.

**Comment by programmingisanart** [comment]
Same behavior here. In my case is a conflict between ioncube and xdebug :(  It seems that xdebug is not compatible with ioncube anyhow, but this behavior -i.e rewriting the content of php.ini - is  unexpected/puzzling for me.

**Comment by easyphp** [comment]
You can change that by modifying the file `eds-app-action.php` (in `eds-binaries > php > phpxxx`).

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @billyrud @programmingisanart
