### ISSUE TITLE
Dashboard shows Notice: Undefined index: display

### ISSUE THREAD

**Issue by Dgame** [easyphp/DEVSERVER#109]
Dev-Server 17.0: Notice: Undefined index: display in eds-app-dashboard.php on line 113

**Comment by easyphp** [comment]
Strange. This file doesn't exists in Devserver. Did you change something ? Which version are you using ?

**Comment by Dgame** [comment]
Apparently it's in the PHP component:
![easyphp-bug](https://cloud.githubusercontent.com/assets/2406877/25771138/5532b5ae-3249-11e7-93f6-20c641d4f9b8.png)

**Comment by easyphp** [comment]
Oh, my bad, you're right. It's a bug.
You can change the line 113 by : 
```if (isset($_GET['display']) AND  $_GET['display'] == 'serverconffile') {```
