### ISSUE TITLE
Undefined Offset when trying to start servers

### ISSUE THREAD

**Issue by mcnjr** [easyphp/DEVSERVER#112]
![image](https://cloud.githubusercontent.com/assets/9257635/25870982/d44340c0-34ba-11e7-8076-fd26a9491d81.png)

I'm working on transitioning from devserver 14 to 17 and got this message the first time I started up easyphp. Did I miss setting something somewhere?

Any help would be much appreciated.

Thanks!

**Comment by ahmedzen2015** [comment]
Hi,

I have the same problem . Could you give us advices to fix it.

Thanks

**Comment by GBrichan** [comment]
I'm having the same problem. Anyone with an idea how to fix?

**Comment by animefr** [comment]
j'ai le même problème, et les serveur ne démarre pas pour moi.

Toujours pas de solution à donner ?

Merci d'avance.

**Comment by GBrichan** [comment]
Just to let the EasyPHP code jockeys know...
EasyPHP Devserver 17 will NOT start either http server or database server with this error happening.
Please look into this. A fix would be GREATLY appreciated.
Thanx large.

**Comment by hpz** [comment]
I tracked down what was happening on my Windows 10 when trying to run Devserver 17 and found the following. The errors appear when the attempt to run eds-app-list.exe from the EasyPHP-Devserver-17\eds-dashboard fail due to Performance Counters being disabled. If you run that from a command prompt from that directory and get a message about performance counters, you may have to edit the following key in the windows registry.

HKEY_LOCAL_MACHINE>SYSTEM>CurrentControlSet>Services>PerfProc>Performance>Disable Performance Counters and set REG_DWORD to 0.

I'm not a windows guy so there may be a better way to do that but that seemed to work for me.

**Comment by mcnjr** [comment]
Hmm, I'm on windows 7 and gave this a shot, didn't seem to change anything for me. Will keep trying things, thanks for the tip! Hopefully it helps someone.

**Comment by hpz** [comment]
What do you get when you open a command prompt and enter this (or wherever you might have Devserver 17 installed)?
Run this from cmd.exe: 
````
c:\Program Files (x86)\EasyPHP-Devserver-17\eds-dashboard\eds-app-list.exe
````

**Comment by mcnjr** [comment]
It says:

"Processor performance object not found on US-58M6K72
Try running Exctrlst from microsoft.com to repair performance counters."

My registry looks like so:

![Registry Values](https://cloud.githubusercontent.com/assets/9257635/26416636/76988f40-406b-11e7-8c90-21df048f3e08.png)

**Comment by mcnjr** [comment]
Ah! I've got it! So in absence of the registry value, opening a command prompt (run -> cmd.exe) (I ran it as an administrator, that might help) and then ran "lodctr /r" and it worked! Hopefully this works for other people. It looks like the registry option is also valid if you're on Windows 10. Thanks for your help @hpz!

**Comment by Nacrox** [comment]
Hi,
I have the same issue and got this message when i tried to run lodctr /r
![capterr](https://user-images.githubusercontent.com/36741478/36556161-234861c6-17fc-11e8-903d-1a0a2923c6fd.JPG)

I was able to access temporarily my site by setting the counter to 0 as instructed by hpz  but I can't do it anymore now.
should i change something, a system resore can fix it ..Please helps!
Thanks.

**Comment by edgaromanito** [comment]
i just used this on my cmd "lodctr /r" its working. Thanks guys!

**Comment by Nacrox** [comment]
Hi edgarmanito,
Do I have to be on a specific folder to run this command ? Do i need to modify something..? thanks in advance.

**Comment by Elnopelado** [comment]
lodctr /r" its Working!!!!! Windows 7

**Comment by l33t-daniel** [comment]
I created this small program in batches, for me it solved and normally starts the HTTP SERVER and the Database.
Super direct, just press Y and go!
Then close your EasyPHP and open it again.
Start all servers.
Ready!

Any problems answer here.
Download Link: [](https://drive.google.com/file/d/1B7besuq7iXwLzKM9enNpREtLav6aI0ZN/view?usp=sharing)

**Comment by fredj737** [comment]
Thank you Daniel you save my life. It work great for me thanks to your program. I would like to give you the love on facebook,  but I don't remember your company name,  I don't want to run the program again. Anyway this world need people like you. Congratulation!!!

**Comment by sterlingdp** [comment]
doesnt work

**Comment by l33t-daniel** [comment]
sterlingdp, run the batch program, then restart your EasyPHP, and run the HTTP SERVER and DB on the easyphp Panel. Ready!

**Comment by sterlingdp** [comment]
Sorry for my ignorance.... what is the batch program? and how do I run it? Also i can't see where to restart easyphp (or is that done be restarting the computer?) Thanks for any help!

**Comment by Lilxam** [comment]
Works for me thanks a lot !

**Comment by marcusgregory** [comment]
Works for me too, thanks!

**Comment by blachawk** [comment]
Not to take away from the miracle program from Google Drive, but can anyone actually "decipher" what the actual error is alluding to in EasyPHP Dev Server?  Or why it shows up out of nowhere?

**Comment by xWinnS** [comment]
> I created this small program in batches, for me it solved and normally starts the HTTP SERVER and the Database.
> 
> **Step 1** - Download the link file:
> Download Link (update): https://drive.google.com/file/d/12rP6-UM2OxO9Qmyn3FHI6AsGSOk4Avni/view?usp=sharing
> 
> **Step 2** - As administrator authorization is required, authorize it.
> 
> **Step 3** - On the screen click "Y" to continue ("N" to exit), and wait for the process;
> 
> **Step 4** - Go to the options to start the servers in the icon that is in the system tray, or go to Dashboard and refresh the page, then start the servers in the HTTP and DB buttons.
> 
> Success to all!

THANKS

**Comment by michelsampil** [comment]
I've tried everything listed above and sadly nothing has worked.

My Solution was moving the EasyPHP-Devserver-17 folder from "Program files x86" to "Program files" folder. re-run and just worked!

Good Luck! it's not a straight forward error.

**Comment by Steakache** [comment]
Yes, thanks @michelsampil. 
I did the test and **renaming the folder works**.
If I put back the original name (Program files x86) the problem appears again.

**Comment by davidan2897** [comment]
Hello everybody, I tried everything that everybody wrote in this thread, but anything function, what helps me,was when you are installing the EasyPHPSerVer-17 , choose the file C:\Program Files , to install, and then it works.
I was installing in (Program files x86) and it doesnt function. You should choose the file when you are installing because if you move the file then of installing it doesnt work.

**Comment by pierreminiggio** [comment]
> Ah! I've got it! So in absence of the registry value, opening a command prompt (run -> cmd.exe) (I ran it as an administrator, that might help) and then ran "lodctr /r" and it worked! Hopefully this works for other people. It looks like the registry option is also valid if you're on Windows 10. Thanks for your help @hpz!

Thanks for this comment.
This is what fixed my issue.
