### ISSUE TITLE
Re-order Virtual Hosts Manager by vhost_name

### ISSUE THREAD

**Issue by fhfournier** [easyphp/DEVSERVER#131]
Its not a issue but a nice feature. Re-order the list of virtual host by vhost_name!

`uasort( $vhosts_array, function( $a, $b, $c = 'asc' ) {
	$a = $a[ 'vhost_name' ];
	$b = $b[ 'vhost_name' ];
	if ( $a == $b ) :
		return 0;
	elseif ( $a < $b ) :
		return ($c == 'asc' ? -1 : 1);
	else :
		return ($c == 'asc' ? 1 : -1);
	endif;
} );`

**Comment by easyphp** [comment]
A new version is out : Virtual Hosts Manager 2.0. This version needs Apache 2.4.48.
It won't be possible to sort the list. But it's on the todo list.
Downaload : https://warehouse.easyphp.org
