### ISSUE TITLE
MySQL server cannot be stopped and restarted when the root user has password

### ISSUE THREAD

**Issue by lllopo** [easyphp/DEVSERVER#132]
I couldn't find a way to set the MySQL root password and so - the database server cannot be restarted, unless I add the password parameter to the php start/stop scripts manually.

**Comment by REJack** [comment]
You can set a root password trough phpMyAdmin there are two ways for it 😄. 

Open phpMyAdmin and select the SQL tab. Then type this command:
`SET PASSWORD FOR root@localhost = PASSWORD('your_root_password');`

Or open phpMyAdmin select User accounts then click on Edit privileges beside your desired account, then select Change password and there you can set a new password.

**Comment by lllopo** [comment]
Well ... that is pretty clear for everyone. The thing is that I don't see a way to set this very same password in the EasyPHP manager. So, having the stop script like this :
`exec('"' . __DIR__ . '\bin\\mysqladmin.exe" -uroot shutdown');`
means you cannot shut it down, once you have only root logins with password. What is needed is a setting in the EasyPHP dashboard what is the password and a vairable in the sciprt like this :
`exec('"' . __DIR__ . '\bin\\mysqladmin.exe" -uroot -p'.$password.' shutdown');`
for example ... or am I missing something ?

**Comment by REJack** [comment]
What I'm not understanding is why do you want a password on your development server? You need no password for development that's why there is nothing for set a password.

But if you want to use a password your line should work, if you set the variable `$password` before you want to use it.

**Comment by REJack** [comment]
I personally wouldn't set a root password, its better to create a new user with a password.

**Comment by lllopo** [comment]
It is sort of a shared dev server, which I'm allowing to be used by several other coleagues in the office (and I have a different user with password for each user database), but anyway - I don't believe that's the point of the discussion, I have my reasons just probably as some other users would have. Question is, that my line works, of course, since I'm already using it, but how about adding this for everyone and without having to mess with scripts changes ?
