### ISSUE TITLE
Can't start database server (MySQL) Only HTTP (Apache) server runs

### ISSUE THREAD

**Issue by abhigyantiwari** [easyphp/DEVSERVER#137]
After going to dashboard I can only start HTTP server (Apache) but when clicking the start button for database server (MySQL) it just refreshes page and does nothing.

Ran program as admin.
I've checked other installations or running processes of MySQL.
Checked port 3306 which isn't used.
Installed all required Visual C++ libraries.
Tried to change port in configuration file of MySQL.
But nothing worked yet.

Snapshot (HTTP runs, clicking start button for database server just refreshes page):

![capture](https://user-images.githubusercontent.com/16822592/31859491-7de66782-b72a-11e7-97d6-a6fee27ad8c1.PNG)
  
Error log shows nothing:

![capture](https://user-images.githubusercontent.com/16822592/31859527-eec5d99c-b72a-11e7-84cf-e752b4ee62d3.PNG)

### Config file content...

[client]
port = 3306

[mysqld]
(comment)Path to installation directory. All paths are usually resolved relative to this.
basedir = "C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/dbserver/mysql5717x86x171022122026/"

(comment)Path to the database root
datadir = "C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/dbserver/mysql5717x86x171022122026/data/"

(comment)The default storage engine that will be used when create new tables
default-storage-engine = MYISAM

bind-address	= 127.0.0.1
socket			= "C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/dbserver/mysql5717x86x171022122026/mysql.sock"
log_error 		= "C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/dbserver/mysql5717x86x171022122026/data/mysql_error.log"

sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES 

[Here ](https://drive.google.com/open?id=0B4P21fQTrcj_VHF1ak15VUx3Zmc)is link to log of my processes, services & software. (Too long that's why link)

**Comment by vincentmrose** [comment]
Hi, I've had the same issue for the last hour and for me a manual start of the MySQL Server seems to have fixed it.
I navigated to the MySQL binary folder and just executed the `eds-dbserver.exe` once.
Now I can start and stop the server over the dashboard.

**Comment by mongamef** [comment]
I have the same issue, but launching eds-dbserver.exe hasn't corrected the issue. Please advise

**Comment by pacificbouk9** [comment]
Salut moi aussi j'ai du mal a lancer le httpserver et le dbserver, juste la page qui s actualise et rien ne se passe

**Comment by GiuliaMarra** [comment]
I know it is an old thread, but I had a similar problem. I solved it by adding the mysql bin ( C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/dbserver/mysql5717x86x171022122026/bin) directory to the PATH system variable (system->environment variables-> select PATH-> edit -> add path to bin).
