### ISSUE TITLE
ERR_CONNECTION_REFUSED 127.0.0.1:1111 - Dashboard not opening

### ISSUE THREAD

**Issue by socialpilgrim** [easyphp/DEVSERVER#149]
Just did fresh installation and tried running server/dashboard - dashboard didn't open.

http and db server/phpmyadmin is running fine.

Checked httpd.conf file for configuration but didn't get any entry for port 1111

**Comment by PaulStaden** [comment]
Had the same problem. Just restarted computer and all worked fine.

**Comment by hungvu9393** [comment]
already reset but nothing happens

**Comment by JulioSilva15** [comment]
Acontece este problema no meu e não consegui resolver

**Comment by SamanthaBeatriz** [comment]
i tried restart the servers but nothing happen.
please could someone help me?

**Comment by gogi100** [comment]
can i change ip address of dashboard?

**Comment by CyrilCharlier** [comment]
i think i have the same issue : #178

**Comment by MarcBeaudoinM9** [comment]
Old subject I know but has anyone figured another solution?  I am trying to deploy EasyPHP via SCCM.  Installation works fine but on each and every computer the dashboard would not start.  I have tried a lot of things, including rebooting, starting as an administrator, manually starting eds-dashboard.exe but to no avail.

Well after a lot of tries it works, but I cannot seem to find why it suddenly end up working, it's like magic every time.  What I have noticed though is that when it works, I can see eds-dashboard.exe taking a port in tools/open ports controller.

**Comment by spuglisi** [comment]
lol

**Comment by sohan5005** [comment]
Old but sharing my case. Dashboard was working for me, I just changed port of HTTP server and it started working again.

**Comment by mateusattri** [comment]
Try to kill all process and then initialize EasyPhp in administrator mode. It works to me ::)
