### ISSUE TITLE
Fatal error on HTTP SERVER dashboard

### ISSUE THREAD

**Issue by Crohm007** [easyphp/DEVSERVER#157]
Hello,

I installed **EasyPHP 17.0** on Windows 10 (64 bits).
It worked very well during several months.

But today, I see the following **fatal error** when going to the **HTTP SERVER > Apache 2.4.25 x86** dashboard : 
![image](https://user-images.githubusercontent.com/17528103/39305680-37b4f6d6-495e-11e8-9f35-4762aa79abdd.png)

I noticed other strange issues at the same time (I don't know if it is related). For example, "localhost" on a browser was not found any more which force me to edit httpd.conf to modify ServerName and Listen properties to "localhost:8080" to be able to execute my pages again... I still don't know why.

I tried to increase the limit to **512MB** in php.ini file but nothing changed.

I am considering switching to **Apache 2.4.33** but if you have any other clue, that would be great.
Thanks a lot.

**Comment by sessionstudio** [comment]
In my case, it was because Easyphp was trying to load a too large error.log file.
Deleting the server log file in eds-binaries\httpserver\apache2418x160331124251\logs
