### ISSUE TITLE
Opening dashboard sometimes restarts Apache httpd on different port (8000 or other)

### ISSUE THREAD

**Issue by Chealer** [easyphp/DEVSERVER#160]
I setup Apache to run on port 8080 instead of the default port number 80. When I launch EasyPHP Devserver 17.0's dashboard, very often the port is changed to 8000 against my will.

When I notice this, I simply need to click on Server Settings, reselect port 8080, then click the "restart" button. Until next occurrence.

**Comment by Sonicelo** [comment]
What I noticed that might be related, not only whenever an error occurs like the post owners, but when automatically restarting for whatever reason (for example activating/deactivating xDebug) it changes the Apache port. I usually work on 80 and it always changes to 8080, seems like its next in the list.
Probably the check for used port is too early?
