### ISSUE TITLE
Home index.php error.

### ISSUE THREAD

**Issue by rhernandog** [easyphp/devserver#17]
Hi,

When I go to

localhost/home/index.php

I'm getting the following error:

```
Parse error: syntax error, unexpected 'Pragma' (T_STRING), expecting ')' in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\home\notification.php on line 8
```

Finally line 8 on the notification.php file looks like this:

```html
<meta http-equiv='Pragma' content='no-cache'/>
```

Thanks for any help,
Rodrigo.

**Comment by easyphp** [comment]
Temporary bug due to a wrong notification format.
