### ISSUE TITLE
Working Directories does not work with OneDrive in Windows 10 1903

### ISSUE THREAD

**Issue by dustojnikhummer** [easyphp/DEVSERVER#177]

**Comment by easyphp** [comment]
Description ?

**Comment by dustojnikhummer** [comment]
Sorry, had to take it down (I did not black out my info correctly).
https://imgur.com/a/3VUMnSB

I'm getting this. I no longer use 1903 (I had to revert because of this).
This has been happening since 1903 launched in Preview Insider Ring.
The issue happens both on Personal and Business (My school in this case) OneDrive.

**Comment by easyphp** [comment]
Did you try to stop your sync app ("pause syncing")? Your sync app locks the files.

**Comment by dustojnikhummer** [comment]
You mean stop Onedrive sync? I don't think so. I will install 1903 in a VM and will report back ASAP.
I don't pause sync in 1809 and before and it works just fine.

**Comment by easyphp** [comment]
Yes, pause or stop Ondrive Sync. Did you try ?
"The process cannot access the file because it is being used by another process"
The file is locked by Onedrive sync.

**Comment by dustojnikhummer** [comment]
I tried both Pause Sync and exiting OneDrive app completely. Now a slightly different error
https://imgur.com/a/CBn3eX1
Pointing to just my OneDrive root directory with test.php file in it.

**Comment by dustojnikhummer** [comment]
Any updates?

**Comment by Stefino76** [comment]
I have the same problem. Any solution?

**Comment by heitih** [comment]
And I have same problem.

**Comment by MatheusPereiraDaSilva** [comment]
I have the same problem

**Comment by Stefino76** [comment]
I've found a workaround with mklink MS-DOS command.
If you want to test it, you have to create a "local folder" out of OneDrive and use it with Easyphp. Then, run cmd as administrator and launch the command:
mklink  /j "local folder" "new folder in OneDrive"
The "new folder in OneDrive" will be creating automatically.
[Here](https://www.computerhope.com/mklink.htm) you can find mklink command documentation.
From now on every change in "local folder" will make a change in "new folder in OneDrive" too, so you have your "local folder" syncing with OneDrive.
If you have others pc with the OneDrive folder issue, you can use mklink to link a local folder to "new folder in OneDrive". If you have a pc without OneDrive folder issue instead, you can use "New folder in OneDrive" directly with Easyphp without errors.
I hope this help you!
