### ISSUE TITLE
Platform upgrade information

### ISSUE THREAD

**Issue by StaggerLeee** [easyphp/DEVSERVER#21]
Where is a tutorial how to upgrade whole easyphp-devserver platform ?
I know I can start exe, but what if databases get ruined. 

Some short info should be somewhere on official website. If nothing to calm and relax Users.

**Comment by easyphp** [comment]
Hi. We will do a proper documentation soon.

**Comment by StaggerLeee** [comment]
Thanks. I see now (after upgrade) many things are different and tutorial is needed. Mysql upgrade, how to do it, etc...

Please activate Curl dll in PHP as default. WordPress cannot update core, themes and plugins without it.

**Comment by Grace-n-Ease** [comment]
Ridiculous people put out software claiming it is "easy" but it isn't, and then don't consider adequate documentation for implementation and upgrade. Shame on you. I have used easyphp for three years. The latest version is impossible to install. All kinds of notices of application unable to load. Get on the ball and provide some decent documentation to help people upgrade. I even paid for your warehouse junk. And it is basically junk now.

**Comment by joluga** [comment]
Is there a place where this upgrade documentation exists? I been using v14 and and want to upgrade to the latest version. It is safe? There is a method to do it? or just hit the .exe?

**Comment by Grace-n-Ease** [comment]
My comments always get deleted.

I would like to know what their definition of "soon" is. "We will do proper documentation soon." in January of 2016 was over a year ago. I have never been able to successfully use v16.1 on any machine. Works one moment, doesn't the next. Went back to v14.
