### ISSUE TITLE
MSVCR110.dll error still happening after installing Visual C++ Redistributable

### ISSUE THREAD

**Issue by AlohaSteam** [easyphp/DEVSERVER#216]
Hello, i'm using the devserver version 17 and i encountered a problem where it said something with MSVCR110.dll. So i googled it and found my fix, or so i thought. And I installed it, tried opening it. Still didn't work. Restarted my computer, and still doesn't work.

**Comment by AlohaSteam** [comment]
Update: Just tried to reinstall the program and nothing happened.

**Comment by DgTone** [comment]
Hello, I have the same error currently, still not resolved?

**Comment by AlohaSteam** [comment]
@DgTone i resolved it, from what I remember it was because I was using the wrong version of Visual C++, I recommend uninstalling all instances of Visual C++ and restart your computer, then go onto the page of easyphp and find your version that you’re using and find the instance of Visual C++ it’s built off of, then downloading the 32 and 64 bit if you have a 64 bit computer. Restart your computer and launch easyphp. Should be fixed

**Comment by JLDR69** [comment]
I have got the same issue. I spent on it the day. I run windows 10 pro 64 bits FRench Edition. I try to get installed Devserver 17.0 and 16.0 without any success. However, I have unloaded and installed the latest Redistribuable Visual C++ pour Visual Studio 2015 French edition.  took care after installing them to reinstall the devserver 17.0 or devserver 16.0 but was not able to run it. I have this regular message that appears : you have a missing msvcr110.dll. I have 2 msvcr110.dll installed :
One is under C:\Programmes\Microsoft Office\root\vfs\System and the other one under directory : C:\Programmes\Dell\SupportAssistAgent\PCDr\Support. I tried to copy one under Windows\System32, but the install process does seem to find it as I got the same error : msvcr110.dll missing.
Is there please a way to configure Devserver 17.0 so that it finds the missing dll.
Please Advice. Thank you

**Comment by AlohaSteam** [comment]
> @JLDR69 like I said above, on the easy php website there is a curtain version of visual c++ the build version works off of, when you go to the website somewhere on the devservee 17.0 download page will show you what version you need. Google it and download the version from the Microsoft page and download and install both the 32 bit and 64 bit Version no matter if you have a 32 bit or a 64 bit computer. Make sure no instances of EasyPHP are running and you’ve uninstalled all instances of Visual c++ and restarted your computer. From there if you install the correct build of Visual c++ you’re easyphp should work. It’s what worked for me.

**Comment by JLDR69** [comment]
Hello Thanks for your reply. Here is what I did this morning on my windows 10 Pro 64bits Dell laptop :
1)Uninstall of EasyPHP 12.1 that worked perfectly==>reboot
2)Uninstall of all versions and instances of Microsoft Visual C++ 2015 redistributable 14.0.23026 ==>reboot
3) Install of VC_redist.x64.exe and VC_redist.x86.exe ==>reboot
4)Install of EasyPHP Devserver 17.0 as an administrator : C:\Program Files (x86)\EasyPHP-Devserver-17
5)Reboot
6)Launch of EasyPhp DevServer 17 ==> Erreur MSVCR110.dll missing
Any help is much appreciated

**Comment by AlohaSteam** [comment]
From the easy php website this is the instance of visual c++ that the devserver requires, I’m currently on my phone but if you still don’t resolve the issue from the link below I will jump on my pc and search what version I have.

http://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by JLDR69** [comment]
HI Thanks for the link. I first downloaded the French version from this url : https://www.microsoft.com/fr-FR/download/details.aspx?id=48145, get them installed both, rebooted and installed devserver 17 without any prior version of easyphp
selecting the French version. After rebooting and launching devserver, I obtained : msvcr110.dll missing.
Thinking it was a problem of FRench version for Microsoft Visual C++ 2015, I uninstalled everything and rebooted. 
Then installed on my windows 10 pro 64 bits French version, the English version from the URL you provided  
http://www.microsoft.com/en-us/download/details.aspx?id=48145, get them installed both x86 and 64bits, rebooted and installed afterwards, the devserver 17.0, rebooted and launch easyphp ==>same problem : missing msvcr110.dll
Devserver 17.0 gets installed under \Programs Files(x86) and msvcr110.dll in no case gets installed under Windows\System32.
Please advice.
*Thanks

**Comment by AlohaSteam** [comment]
After doing some reading apparently it requires the 2015 version of Visual C++ but what the website doesn’t state is it requires the 2012 version too, I linked below the 2012 version of Visual C++, hopefully this time it works

https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by luavergi** [comment]
> After doing some reading apparently it requires the 2015 version of Visual C++ but what the website doesn’t state is it requires the 2012 version too, I linked below the 2012 version of Visual C++, hopefully this time it works
> 
> https://www.microsoft.com/en-us/download/details.aspx?id=30679

Thanks guys for your dialogue it worked out for me that way too!
