### ISSUE TITLE
Dashboard must be started via CMD

### ISSUE THREAD

**Issue by dldnet** [easyphp/DEVSERVER#227]
Hi all,

I have installed EasyPhp on a USB stick. Everything works fine except the dashboard.
It is never started when I launch EasyPhp and it is never started when I click on "Open dashboard" in the system tray app.
Indeed, when I open a cmd and start manually eds-dashboard.exe it works perfectly.

As there is no difference between the command in the run-devserver.ini and the command I type in the cmd...
I don't understand.

I use it sometimes in my classroom and it is not easy to explain to students how to start with a cmd box just at the beginning.

Do you have a solution ?

Thanks in advance

**Comment by easyphp** [comment]
You still have this problem ?
