### ISSUE TITLE
zend_extension preg_replace

### ISSUE THREAD

**Issue by chgsantos** [easyphp/DEVSERVER#231]
Hi!

When I edit my `php.ini` file including a custom `zend_extension`, the `eds-app-actions.php` file replaces it to `php_xdebug-xxx.dll`.

I suggest changing the following lines of `eds-app-actions.php` from:
```php
// zend_extension - xdebug dll
$replacement = '${1}' . __DIR__ . '\\' . $php_settings['xdebug_dll'] . '$3';
$phpini = preg_replace('/^([\s|\t]*zend_extension[\s|\t]*\=[\s|\t]*\"[\s|\t]*)(.*)(\".*)$/m', $replacement, $phpini);
```

To:
```php
// zend_extension - xdebug dll
$replacement = '${1}' . __DIR__ . '\\' . $php_settings['xdebug_dll'] . '${5}';
$phpini = preg_replace('/^([\s|\t]*zend_extension[\s|\t]*\=[\s|\t]*\"[\s|\t]*)((.*)xdebug(.*))(\".*)$/m', $replacement, $phpini);
```

Example of custom `zend_extension`:
```ini
zend_extension = "C:\EasyPHP-Devserver-17\eds-binaries\php\php5630vc11x86x170607172225\ioncube\ioncube_loader_win_5.6.dll"
```

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need.

**Comment by easyphp** [comment]
Problem fixed with the new version. Xdebug manager 3.0 will be released in early September.
