### ISSUE TITLE
Apache 2.4.48 Won't Start

### ISSUE THREAD

**Issue by elogicmedia** [easyphp/DEVSERVER#247]
I'm trying to get easyPHP to work with the virtual hosts manager. Running earlier versions of apache will start up without issue, as soon as I try to start Apache 2.4.48 it doesn't do anything. The page refreshes and the start button is still green. No errors come through in the apache logs to help debug.

I'm wondering if this is due to the fact that I could only find Apache 2.4.48 in x64? Is there an x86 version of Apache 2.4.48 so I can then use 'virtual hosts manager' ? Otherwise, is there a way I can debug to see why this version of apache won't start?

Thanks

![x64Screenshot 2021-09-30 105835](https://user-images.githubusercontent.com/510943/135368508-3f6e60db-9c23-4ed9-81c6-bb30619a66f5.png)

Don't know if this helps, there is a console error that says:

Uncaught Error: ace.edit can't find div #editor_php
    at Object.t.edit (ace.js:1)
    at index.php?zone=applications&page=httpserver&serverfolder=apache2448vc15x64x210930104050&display=servererrorlog:299

**Comment by tapsystem** [comment]
i got the same problem, do you find a solution ?

**Comment by elogicmedia** [comment]
Nope, never found a solution or get a support response. Decided to stop using this product and went to WAMP.

**Comment by tapsystem** [comment]
> Nope, never found a solution or get a support response. Decided to stop using this product and went to WAMP.

Thanks for feedback, i've made the same transition this weekend and start installing WAMP too

**Comment by gogo740618** [comment]
I had the same issue. Just had to find what is keeping ports open. Download Open Server ( https://ospanel.io/download/ ) - 
it will tell you when you try to start it what ports are open and by what program. Or even you can switch using it
