### ISSUE TITLE
Não consigo iniciar o servidor de banco de dados

### ISSUE THREAD

**Issue by Devfox123** [easyphp/DEVSERVER#249]
Aviso: Variável indefinida: conf_dbserver em C:\Arquivos do Programa (x86)\EasyPHP-Devserver-17\eds-dashboard\index.php on line 368

Aviso:include(C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\dbserver\\eds-app-settings.php): não abriu o fluxo: Nenhum arquivo ou diretório em C:\Arquivos do Programa (x86)\EasyPHP-Devserver-17\eds-dashboard\índice.php na linha 368

Aviso: include(): Abertura falha 'C:\Arquivos do programa (x86)\EasyPHP-Devserver-17\eds-binaries\dbserver\\eds-app-settings.php' para inclusão (include_path='. C:\php\pear') em C:\Arquivos do Programa (x86)\EasyPHP-Devserver-17\eds-dashboard\índice.php na linha 368

Aviso: Variável indefinida: conf_dbserver em C:\Arquivos do Programa (x86)\EasyPHP-Devserver-17\eds-dashboard\índice.php na linha 406

**Comment by easyphp** [comment]
Could you describe the problem in English ?
