### ISSUE TITLE
Easy PHP 17 My SQL & Database Server

### ISSUE THREAD

**Issue by dario7755** [easyphp/DEVSERVER#251]
Hi :-)
I have installed Easy PHP 17 & on it Database Server & MySQL 5.7.17. When I'm trying to start Database Server & MySQL 5.7.17 it doesn't work, why ? 
D.J.
p.s: I have also HTTP Server Apache 2.4.25 and it works ok on that Easy PHP 17.

**Comment by easyphp** [comment]
Hi. What do you mean by "it odesnèt work" ? Any error message ? Any log ?
