### ISSUE TITLE
EasyPHP Devserver 17 + Virtual Hosts Manager 2.0: can't activate VH

### ISSUE THREAD

**Issue by albertopasian** [easyphp/DEVSERVER#253]
Hi, as for the subject, I'm running EasyPHP Devserver 17 with Virtual Hosts Manager 2.0. 
Apache 2.4.48 and MySQL 5.7.17 are running just fine.
I can add new Virtual Hosts but it seems I cannot activate/deactivate them; also the two HTTP/HTTPS switches don't work.

![EasyPHP Devserver](https://user-images.githubusercontent.com/53472022/142633010-4abfc204-f584-47d0-9348-1c0d8a97ca8f.png)

Thanks in advance for any help.

**Comment by easyphp** [comment]
Hi.
Are you sure the server is running.
From the screenshot, it looks like the server is down.

**Comment by WmOne** [comment]
please, can u let me know how you cuold install vhost man. 2.0 with devserver 17 ?
my installed vhm 2.0 ask me to upgrade apache to 2.4.48versione, but this version is only 64 Bit, while devserver is 32 bit
