### ISSUE TITLE
Multiple issues with xdebug on php 8.0.x & 8.1.x - #2 - xdebug 3 support

### ISSUE THREAD

**Issue by sbulen** [easyphp/DEVSERVER#256]
Note that the xdebug parameters in php.ini have been completely redefined in xdebug 3:
https://xdebug.org/docs/upgrade_guide#Changed-Configuration-Settings

What this means is that:
(1) The xdebug manager module does not work at all
(2) The default xdebug values in php.ini need to reflect xdebug 3 syntax

The workaround is to deinstall the xdebug manager module, to modify php.ini as suggested on the xdebug.org site by hand, and to restart apache/php for the new settings to take effect.

**Comment by sbulen** [comment]
All EasyPHP 8.0.x versions are affected by this.

**Comment by sbulen** [comment]
In case it helps, after some experimentation, this is the set that has worked for me:
```
zend_extension="C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php8013vs16x64x211128091357\php_xdebug-3.1.1-8.0-vs16-x86_64.dll"
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=127.0.0.1
xdebug.client_port=9003
xdebug.idekey=ECLIPSE_DBGP
xdebug.dump_globals=1
xdebug.dump=COOKIE,FILES,GET,POST,REQUEST,SERVER,SESSION
xdebug.dump.SERVER=REMOTE_ADDR,REQUEST_METHOD,REQUEST_URI
xdebug.show_local_vars=1
xdebug.trace_options=0
xdebug.trace_format=0
xdebug.trace_output_name="trace.%t"
xdebug.profiler_output_name="cachegrind.out.%s.%t"
xdebug.output_dir="C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\xdebug"
;xdebug.log="C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\xdebug\xdebug.log"


```

**Comment by sbulen** [comment]
What's nice about the new architecture is that once the .dll is involved, you can choose among the various options by simply setting xdebug.mode.  No need to rewrite php.ini & restart apache.

I think all we need to do under xdebug3 is load the .dll like any other extension, then use ini.set calls for the xdebug mode.

Values are: off, develop, coverage, debug, gcstats, profile, trace

https://xdebug.org/docs/all_settings#mode

**Comment by easyphp** [comment]
Hi. It's on the to-do list. It should be included in the next version of the components. Thanks.
And we will recompile the other versions.

**Comment by spem** [comment]
I install on Windows 10, all setings on instalation are defaults dont change anyting, Upgrade Apache e PHP and some modules, and get this error and cant start Xdebug
![image](https://user-images.githubusercontent.com/2519491/168446018-8ee8aa8b-6563-4316-af13-e892ed97c0f3.png)

**Comment by easyphp** [comment]
It will fixed with the new version. Xdebug manager 3.0 will be released in early September.
