### ISSUE TITLE
can't get the devserver dashboard to open in any browser

### ISSUE THREAD

**Issue by DragonMichael** [easyphp/DEVSERVER#260]
Trying to finish setting up the MySQL server part of the devserver installation, but can't get the dashboard to open to finish configuring it. The connection is being refused and the directions to try and rectify the situation isn't giving correct directions to be able to remove and re-add the browser as a trusted connection as I still haven't been able to find said list the way the directions indicate. Nor can I find an uninstall option to uninstall the devserver to try and find a better product. An uninstall option should always be included with any software. I need help to either get the dashboard to open to finish configuring the database server part of it or a way to uninstall it all in a way that will free up my ports so they can be assigned to software that can be configured properly.

**Comment by DragonMichael** [comment]
Wow, no responses yet and my anti-virus just quarantined the eds-dashboard.ini file because it was infected with malware.

**Comment by easyphp** [comment]
No malware, it a false positive.

> An uninstall option should always be included with any software.
https://www.easyphp.org/documentation/devserver/how-to-uninstall-devserver.php

Any error message ? We need more information (version, system, logs...).

**Comment by Variavel0** [comment]
I just downloaded EasyPHP and I can't open the Dashboard. The following message appears: 'Cannot access this site'.
Connection to 127.0.0.1 was refused.

I await an answer.

**Comment by easyphp** [comment]
We need more information. Version ? system ? browser ? logs ?

**Comment by DimitarBogdanov** [comment]
Had the same issue. Stopping Devserver and starting it with admin priviledges fixed the issue for me.

**Comment by luavergi** [comment]
Thanks Dimitar that really worked for me as well!

> Had the same issue. Stopping Devserver and starting it with admin priviledges fixed the issue for me.

**Comment by HamzaDerim** [comment]
I downloaded easphp, I cannot install it and when I run it as administrator, the device does not turn on and I also get a server error in open dashboard applications.
