### ISSUE TITLE
Can't select PHP 8.1 in Apache dashboard

### ISSUE THREAD

**Issue by ReLater** [easyphp/DEVSERVER#261]
- Win10 pro x64/64-bit
- I installed EASYPHP DEVSERVER 17.0
- On local drive Z: (Z:\EasyPHP-Devserver-17). Checked that it works.

- Installed PHP 8.1 x64 (64-bit) from warehouse in folder above and saw afterwards:

![grafik](https://user-images.githubusercontent.com/20780646/146239451-32423b51-8a7b-4ccd-84ab-374869534858.png)

and

![grafik](https://user-images.githubusercontent.com/20780646/146240810-9c8d50dd-7f73-4830-96a8-5250f2d8c947.png)

- but I can't select PHP 8.1 in Apache configuration afterwards:

![grafik](https://user-images.githubusercontent.com/20780646/146241058-732df8b3-66b6-40f2-8298-af2ca02408a4.png)

- I've restarted the servers and Win several times. 
- I've reinstalled Visual C++ Redistributable for Visual Studio 2019 x64
- No change.

Do I miss something?

Thank you!

**Comment by sbulen** [comment]
x86 apache only runs x86 php (32-bit).

x64 apache only runs x64 php (64-bit).

**Comment by ReLater** [comment]
I've installed what the download button provided as installation package of "EASYPHP DEVSERVER 17.0" ("for Windows 7/8/10"). I couldn't find any other environment specific package. 
A bit confusing that it installed x86 ;-)
