### ISSUE TITLE
problem with devserver php 8.1.1 and apache 2.4.48 (x64)

### ISSUE THREAD

**Issue by LucasMadranges** [easyphp/DEVSERVER#262]
Hello, i have just installed php 8.1.1 ans apache 2.4.48 and i have this so i can't use php for now please help me
![image](https://user-images.githubusercontent.com/46574254/149001558-88f4b7bf-e072-4f8e-a77d-7dfdb298a4f1.png)

**Comment by easyphp** [comment]
Do you use Virtual Hosts ? Is the file `apache-vhosts.conf` present in the folder `eds-dashboard` ? What's the content ?

**Comment by hassanbouaakab** [comment]
Hi same issue for me any solution for this Thanks.

**Comment by w311s** [comment]
> Do you use Virtual Hosts ? Is the file `apache-vhosts.conf` present in the folder `eds-dashboard` ? What's the content ?

I have the same issue any solution?

**Comment by hassanbouaakab** [comment]
Yes i did fixed the problem you just need to comment the line where the include of the file (apache-vhosts.conf)

**Comment by sodmond** [comment]
I fixed this by copying the this file `C:\EasyPHP-Devserver-17\eds-binaries\httpserver\apache2448vc15x64x230804074202\conf\httpd-vhosts.conf` into this directory` C:\EasyPHP-Devserver-17\eds-dashboard` and renamed it to `apache-vhosts.conf`

**Comment by Goldenhub** [comment]
> I fixed this by copying the this file `C:\EasyPHP-Devserver-17\eds-binaries\httpserver\apache2448vc15x64x230804074202\conf\httpd-vhosts.conf` into this directory` C:\EasyPHP-Devserver-17\eds-dashboard` and renamed it to `apache-vhosts.conf`

This worked for me. Thanks

**Comment by Goldenhub** [comment]
I updated my Apache server to 2.4.48 and my php to 8.1.1.
I am getting this error notice when I start my xdebug manager 1.7.

`Notice: Undefined offset: 1 in C:\Program Files (x86)\EasyPHP-Devserver-17\edsmodules\xdebugmanager\xdebugmanager.php on line 20` 
and
`Notice: Undefined offset: 1 in C:\Program Files (x86)\EasyPHP-Devserver-17\edsmodules\xdebugmanager\xdebugmanager.php on line 34`

what do I do please?

**Comment by easyphp** [comment]
Hi. Problem fixed with the new version. PHP Devserver 24 will be released in early September.
