### ISSUE TITLE
You need Apache 2.4.48 or newer. Visit the warehouse for new versions.

### ISSUE THREAD

**Issue by purplec1rcle** [easyphp/DEVSERVER#263]
I have EasyPHP Devserver 17.0 x86 installed running Apache 2.4.25 and I would like to use the Virtual Hosts Manager but when I install it, I get the error "You need Apache 2.4.48 or newer. Visit the warehouse for new versions." I've checked the warehouse and there is no x86 version of Apache 2.4.48. There is an x64 version but that won't install with the x86 version of EasyPHP Devserver 17.0.

Where do I get the x64 version of EasyPHP Devserver 17.0 or alternatively, where do I get the x86 version of Apache 2.4.48?

I have tried manually downloading Apache 2.4.48 from apache.org and installing it in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\httpserver and then copied all the eds-app-?????.php files from the working Apache 2.4.25 folder to the Apache 2.4.48 folder as well as eds-httpserver.exe from the Apache 2.4.25 "bin"  folder to the Apache 2.4.48 "bin" folder but I cannot get the Apache server to start using the Dashboard. It doesn't throw any errors, it just won't start.

**Comment by WebSpectrum** [comment]
It shoudl work - just make sure you have 64 bit versions of php and apache
