### ISSUE TITLE
Problems connecting to the MySQL server,

### ISSUE THREAD

**Issue by thekiketrue** [easyphp/DEVSERVER#265]
I do not know the host of the dbserver, which default value installs Easyphp in the host variable of a php file.

host = "localhost" or host="127.0.0.1",  none works for me, do you need to indicate a port?

Please I need help in the case, thanks

**Comment by dennisAlexander** [comment]
http://127.0.0.1:8080/  worked in my case, for another project.  Now its not working for a wordpress install, i'm going to download the new pack easyphp let out.  good luck
