### ISSUE TITLE
New Installation on Win 11 - No connection for dashboard

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/DEVSERVER#267]
Hi,
after a fresh install on a Win 11, the apache is up, mysql too but when i go to 127.0.0.1:1111 there is no connection.
![image](https://user-images.githubusercontent.com/11455745/162275939-0d5f1e26-2d3e-431d-8e5f-be098ebe2b92.png)

On port 80 i can see the phpinfo.php file.
![image](https://user-images.githubusercontent.com/11455745/162276013-07ce5acf-8472-479d-af3c-b15a3b666676.png)

How can i do to make it work ?
thnaks

**Comment by flavioureshino** [comment]
I'm having the same problem.

**Comment by CyrilCharlier** [comment]
> I'm having the same problem.

Hi Flavio, after a reboot, i can get the dashboard page. Have you try it ?

**Comment by spem** [comment]
I have the same problem on access to "**127.0.0.1:1111**", so i change to "**127.0.0.1:80**" and works fine.
