### ISSUE TITLE
server rejected the connection phpMyAdmin

### ISSUE THREAD

**Issue by darknova11** [easyphp/DEVSERVER#27]
Hi,
I have instaled the new 16.1 and went in to phpMyAdmin to add pass to users
aftrt that I did add that pass into  $cfg[‘Servers’][$i][‘password’] = ‘ ‘; ”  in config.inc.php 
but I'm unable to login to phpMyAdmin - I get this message:
Welcome to phpMyAdmin

Error
MySQL said: Documentation
#1524 - Plugin '*7E8FFF8502854FCC94EF5D3CE8A8FE1123A5D094' is not loaded

 phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.

Need help please!

**Comment by SublymeRick** [comment]
I'm also having this problem. Every user I create using "grant" sets the password string in the "plugin" column which is not correct. It should be placed in the authentication string column. I may be wrong but this might be caused by the presence of the "password" column as I though mysql 5.7 removed this column from the mysql.user table.

**Comment by eternal-sorrow** [comment]
Have this problem too. It's very annoying.

**Comment by Huehnerbrust** [comment]
Same problem here. I have Devserver 16.1.1, Mysql 5.7.11

**Comment by SublymeRick** [comment]
I figured out how to fix this. After setting up 16.1 or any new version of mysql on 16.1, at least for the time being, you have to go into the mysqld bin folder on a command prompt and type the following command: 

mysql_upgrade -u root --force

**Comment by Oakeson** [comment]
Same problem here, using 16.1 and MySQL 5.7.11. Running mysql_upgrade (as root, forcing upgrade) just leads to a litany of errors about tables that don't exist; restarting services gives the same errors as before

**Comment by dchaykas** [comment]
Opened Jan 18 and this problem is still not resolved? Greatly disappointed.

**Comment by svofusihan** [comment]
Late answer, but can be usefull for others. After a fresh install of EasyPHP DevServer 17.x, I had the same problem. Using PhpMyAdmin 4.7.0 to create a new user on my database, the new user was invalid right after I restart the server. Error "1524 - Plugin '*....' is not loaded".

Actually DevServer installed two versions of PHP, 5.x and 7.x. By default, the version 5 was enable. But since MySQL changed its columns in the users table, as @SublymeRick explained in its first answer, PhpMyAdmin has to run under a more recent version of php (7 for example) to be able to create new users properly.

So go to the EasyPhp settings and select the version 7.x of php. Then, refresh PhpMyAdmin, delete your corrupted users and create new ones. The column "authentication_string" will now contain you hashed password and the column "plugin" will contain "mysql_native_password". The connection will work.

**Comment by REJack** [comment]
Guys check your mysql.log, what kind of error you get?

**Comment by svofusihan** [comment]
@REJack This post is a bit old but I faced the same problem yesterday with the last version of DevServer (17.0). And actually the solution proposed by @SublymeRick is the right one (execute mysql_upgrade -u root --force AND restart the service). But one more thing has to be done on existing database. The mysql users created before the migration have to be deleted and created again. Maybe that's why @Oakeson still had the problem after he executed mysql_upgrade.

**Comment by SublymeRick** [comment]
Honestly I just disabled mysql, installed mariadb native and use HeidiSQL instead of phpMyAdmin. Problem solved 👍

**Comment by Raekon** [comment]
Hi.

I have the same problem as Oakeson and svofusihan but when I try to run Mysql-ugrade, it returns the following error in the prompt

mysql_upgrade: Got error: 2003: Can't connect to MySQL server on 'localhost' (10061) while connecting to the MySQL server
Upgrade process encountered error and will not continue.

Does anyone have an idea what to do (and @SublymeRick I'm not quite ready to install other options just yet :-/)

Thanks.

**Comment by SublymeRick** [comment]
@Raekon Make sure your mysql server is running and connectable.

**Comment by Raekon** [comment]
Thanks. I think that did it (my first instinct was that when you have to alter something, it usually has to be off). That and then deleting the faulty users. I wish I knew why it happened. I altered a table, and the users just 'died' on me...

**Comment by oksana-skotar** [comment]
> @REJack This post is a bit old but I faced the same problem yesterday with the latest version of DevServer (17.0). And actually the solution proposed by @sublymerick is the right one (execute mysql_upgrade -u root --force AND restart the service). But one more thing has to be done on existing database. The mysql users created before the migration have to be deleted and created again. Maybe that's why @Oakeson still had the problem after he executed mysql_upgrade.

**This worked perfectly! Thank you!**

Here is the full description of the case.
I have Easyphp DEVSERVER 17.0. 
Last time when I left the site, it has been working, then when I came back in some days, I had an error.

The error that I had in my logs in file ```
C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\httpserver\apache2425vc11x86x180510203041\logs\error.log
was [Tue Jun 19 15:20:42.833135 2018] [php7:notice] [pid 9984:tid 1300] [client 127.0.0.1:52945] PDOException: SQLSTATE[HY000] [1524] Plugin '*A90B72C4DEEAAE29C276F9421B74C394B11C8963' is not loaded in C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\PhpArrayContainer.php on line 79 #0 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\Database\\Driver\\mysql\\Connection.php(149): PDO->__construct('mysql:host=loca...', 'interiors', 'mypasswordischangedhere', Array)\n#1 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\Database\\Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\Database\\Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\Container.php(171): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\PhpArrayContainer.php(260): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Component\\DependencyInjection\\Container.php(171): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\DrupalKernel.php(514): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\DrupalKernel.php(875): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\DrupalKernel.php(467): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\core\\lib\\Drupal\\Core\\DrupalKernel.php(663): Drupal\\Core\\DrupalKernel->boot()\n#13 C:\\Users\\Oksana\\Documents\\sites\\drupal2\\index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}, referer: http://127.0.0.1:1111/
```
My Drupal 8 site displayed "`The website encountered an unexpected error. Please try again later.`"

I ran the `mysql_upgrade -u root --force` command in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\dbserver\mysql5717x86x180510203041\bin folder with Windows command line, it gave a lot of text with OK statuses and some with errors.
Then I've switched off and then on the database and the HTTP servers with the dashboard.
Then I've deleted user in PhpmyAdmin > User accounts
And created it in (mydatabase) > Privileges > Add user account 
with Authentication Plugin: Native MySQL Authentification, 
and Global privileges.
Then I've reloaded my site and it works.

**Comment by Raekon** [comment]
@oksana-skotar Thank you ever so much... I had a problem, where my site would suddenly refuse the connection with Mysql, giving the "..... module not loaded"-error. 

I followed the instructions at the end of your post, and now it seems to work... 
May your life be long and prosperous. :-)

thank you.

-Raekon.
