### ISSUE TITLE
Subscription not updated

### ISSUE THREAD

**Issue by GeeDeeJay** [easyphp/DEVSERVER#275]
The payment was taken out of my account on 18 March 2022 but the site says my subscriptions has expired.
Could you please update my records.
I have emailed twice now from my registerd email address, which I would prefer not to show here.
Thank you

**Comment by GeeDeeJay** [comment]
I'm disappointed that this request seems to have been ignored.

**Comment by pedroquezado** [comment]
I had a similar problem. I signed up yesterday, and so far I haven't received any email, nor anything guided me to register!!

**Comment by easyphp** [comment]
Hi,
Sorry for this late reply (summer break).
Can you give us the email address you used (we cannot find find your account with your GitHub alias). You can send it there : easyphpdotorg@gmail.com
