### ISSUE TITLE
Replacement config in php.ini work only one "zend_extension" match

### ISSUE THREAD

**Issue by fabriciopolito** [easyphp/DEVSERVER#278]
Hello,
The replacement config in php.ini work only one "zend_extension" match and for xdebug dll (eds-app-settings.php) , but if you need more zend_extension dll not will be saved.

eg: I can not have "zend_extension=php_xdebug.dll" and "zend_extension=opcache.dll" in the same php.ini file because the replacements do not keep it.

**Comment by fabriciopolito** [comment]
I fixed it applying some modifications in **php.ini** and **eds-app-actions.php**

My solution:

To match separated **zend_extension** i added at the end of line a comment that indicates for.

**Step 1**

eg: php.ini to opcache

zend_extension = "C:\EasyPHP-Devserver-17\eds-binaries\php\php7427vc15x86x221012223858\_WILL_BE_REPLACED_WITH_CONFIG_AT_eds-app-settings.php_" **;opcache**

eg: php.ini to xdebug

zend_extension = "C:\EasyPHP-Devserver-17\eds-binaries\php\php7427vc15x86x221012223858\__WILL_BE_REPLACED_WITH_CONFIG_AT_eds-app-settings.php_" **;xdebug** 

Do not forget to add required ";opcache" and ";xdebug" at the end of line to indicates correct  replacement.

**Step 2**

Edit C:\EasyPHP-Devserver-17\eds-binaries\php\php7427vc15x86x221012223858\**eds-app-settings.php** and add one more key to array $php_settings:

eg: 'opcache_dll' =>  "ext\php_opcache.dll"

**Step 3**

Edit C:\EasyPHP-Devserver-17\eds-binaries\php\php7427vc15x86x221012223858\**eds-app-actions.php** and replace:

Origin:

```php
// zend_extension - xdebug dll
$replacement = '${1}' . __DIR__ . '\\' . $php_settings['xdebug_dll'] . '$3';
$phpini = preg_replace('/^([\s|\t]*zend_extension[\s|\t]*\=[\s|\t]*\"[\s|\t]*)(.*)(\".*)$/m', $replacement, $phpini);	
```

To:

```php
// zend_extension - xdebug dll
$replacement = '${1}' . __DIR__ . '\\' . $php_settings['xdebug_dll'] . '$3';
$phpini =                preg_replace('/^([\s|\t]*zend_extension[\s|\t]*\=[\s|\t]*\"[\s|\t]*)(.*)(\"[\s|\t|\;xdebug]*)$/m', $replacement, $phpini);	

// zend_extension - opache dll
$replacement = '${1}' . __DIR__ . '\\' . $php_settings['opcache_dll'] . '$3';
$phpini =                preg_replace('/^([\s|\t]*zend_extension[\s|\t]*\=[\s|\t]*\"[\s|\t]*)(.*)(\"[\s|\t|\;opcache]*)$/m', $replacement, $phpini);
```

Restart DevServer Apache.

**Comment by easyphp** [comment]
Hi. Problem fixed with the new version. Xdebug Manager 3.0 will be released in early September.
