### ISSUE TITLE
Missing file (vhosts.conf) in easyPHP Devserver Apache update 

### ISSUE THREAD

**Issue by MaliyaSketuve** [easyphp/DEVSERVER#279]
Hello,

I had a setup for devserver 17 which worked with apache core V2.4.25 and PHP Version 7.1.3 x86 (32-bit) version. I want to use a PHP Version 8. To be able to do that I added the apache core V2.4.48 (64-bit) and PHP Version 8.1.2.

The issue is that when I try to run Apache V2.4.48 - with PHP Version 8.1.2 x64, I get the following error message :
![EasyPHP_ErrorMsg](https://user-images.githubusercontent.com/119782438/205485639-079ea4a0-8e73-4d9d-97b7-8b238376fb6b.JPG)

Where could I find the missing file 'apache-vhosts.conf' ?
What should it contain?

Even though the production platform will be a Virtualised Linux server, my dev environment being my computer, it doesn't have enough RAM to run any Virtual machine. easyPHP should be a good solution for dev, unless I cannot run the php V8 and over.

Thank you for your guidance.

**Comment by johanguse** [comment]
Same here. Do you have any updates on how to fix it?

**Comment by MaliyaSketuve** [comment]
No I am still blocked. I will save my files, and do a full
uninstall/cleanup reinstall of the devserver. It might help (hopefully).

Le mar. 10 janv. 2023 à 17:26, Johan Guse ***@***.***> a
écrit :

**Comment by easyphp** [comment]
Hi. Problem fixed with the new version. PHP Devserver 24 will be released in early September.
