### ISSUE TITLE
Is EasyPHP devserver 32 or 64 bit?

### ISSUE THREAD

**Issue by Usalabs** [easyphp/DEVSERVER#281]
OK, after downloading the latest easyPHP devserver it installs it into the (Win 10) 32 bit folder "Program files (x86)", which signifies that it's 32 bit, and there is NO 64 bit version available, so why attempt to install 64 bit PHP module when the installer says there is no DevServer located at "Program files" a 64 bit location?

Also, if it only installs in the 32 bit location, then why does the virtual hosts manager insist on Apache 2.4.48, which is ONLY available in 64 bit format, and when I attempt to install it, the Apache module installer says "There is no Devserver in Program Files", a 64 bit location.

Personally, I don't think this platform has been thoroughly thought through, and there are better platforms than EasyPHP, such as WAMP, and XAMPP, for developing and deploying PHP websites, and they work out-of-the-box.

If you're going to create a 64 bit version, then create a 64 bit version to be installed at the 64 bit location "Program files", and if a 32 bit version then create a 32 bit version to be installed at "Program Files (x86)" a 32 bit location, downloading an exe and saying it's both 32 and 64 bit, just don't work.

**Comment by sbulen** [comment]
Note that this platform let's you choose either 64 bit or 32 bit, for both php & apache.

But you need to run 64 bit php on 64 bit apache, & 32 bit php on 32 bit apache.

But the main "menu" that launches everything, 32 bit & 64 bit, needs to be in one location.

**Comment by Usalabs** [comment]
Actually, the platform when installing (EasyPHP-Devserver-17.0-setup.exe) doesn't give the option for 32 or 64 bit, it's default location is "Program Files (x86)" a 32 bit location, and all of the 64 bit module installers default to "Program Files" a 64 bit location, that's assuming the OS is 64 bit, and when a 64 bit module is being installed, it looks at the default 64 bit location and returns an error "There is no EasyPHPdev" at that location, so, if one wishes to install 64 bit modules, then at least have the default location set to "Program Files (x86)" where the main EasyPHP software is located.

**Comment by sbulen** [comment]
It's true it should remember the install directory...  

But it can run either 32 bit or 64 bit, both for DB & for Apache/PHP, enabling you to switch back & forth at will.  My install looks like this - note I can choose either the x64 or x86 Apache:
![image](https://user-images.githubusercontent.com/23568484/217117259-d6d1d47d-9372-4222-b220-c26227c2a3de.png)

And the 32 bit apache only allows the 32 bit PHP:
![image](https://user-images.githubusercontent.com/23568484/217117188-280f5dec-85d1-41c5-9aec-51ca0c760339.png)

**Comment by Usalabs** [comment]
I am aware that PHP and Apache versions can be changed using the dashboard, but that's not the point, the point is, someone that downloads EasyPHP devserver would expect any modules regardless of 32 or 64 bit to be installed into the directory that the main software is installed to, IE "Program Files (x86)" 32 bit location, and would confuse a noob when the 64 bit modules are expecting to be installed at "Program Files" 64 bit location, but instead, during module install, one would 'Browse' to "Program Files (x86)" to install the modules.
