### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by sbulen** [easyphp/DEVSERVER#283]
We're gonna need that, it's been out a while.

**Comment by Sonicelo** [comment]
Agreed!

**Comment by Sonicelo** [comment]
There has been no response from the developer for a while now, and there are quite some open issues around.
I understand this as a side project but still would expect at least some responses from the owner. php version 8.2 for me is becoming a requirement in very near future and I will not be able to use this package anymore which is sad as it was a great balance between configurability, easy of use and stability.

**Comment by GeeDeeJay** [comment]
I've had no response from the developer either. PHP 8.1 is reaching an end in November '23, 8.2 is imperative. I've also been unable the get openssl_encrypt working, and no response regarding that. It is a pity, I've been using easyphp since I started working with php over 20 years ago.

**Comment by GeeDeeJay** [comment]
I see PHP 8.2 is now available, however, the link says it goes to versions for X64 and X86, but the download is only for X64.

**Comment by easyphp** [comment]
Hi. Yes, that's a mistake. It will be fixed soon.

**Comment by GeeDeeJay** [comment]
Does that mean there isn't going to be another version?
Regards
Dave

**Comment by easyphp** [comment]
Just published! PHP 8.2.9 x86 for Devserver is there: https://warehouse.easyphp.org/inventory-devserver#php

**Comment by GeeDeeJay** [comment]
Super! Will get that today.
Thank you.
