### ISSUE TITLE
I cannot download the devserver 1.7.0 on your offical page "https://www.easyphp.org/"

### ISSUE THREAD

**Issue by yurtseverfazli** [easyphp/DEVSERVER#285]
When I try to upload Devserver 1.7.0  I get the error.
The connection is not secure for this sitebbuseruploads.s3.amazonaws.com sent an invalid response.
Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
ERR_SSL_PROTOCOL_ERROR
 
I think it is because "sitebbuseruploads.s3.amazonaws.com" has an ssl problem.
I need your advice.

**Comment by Tim-VL** [comment]
https://bitbucket.org/easyphp/easyphp-devserver/downloads/EasyPHP-Devserver-17.0-setup.exe
