### ISSUE TITLE
Unable to load ext // eds-app-actions.php: extension_dir path failed due to \9

### ISSUE THREAD

**Issue by Florent-ARENE** [easyphp/DEVSERVER#287]
In **eds-app-actions.php**, when the script generated the **extension_dir** path, **\9** was treated as an escape sequence. And since \9 isn't a valid escape sequence in PHP, it simply disappeared from the path. This resulted in generating the wrong path and I was unable to load the extensions.

Instead of:
C:\Users\\**9604817**\Documents\\___WWW\EasyPHP-Devserver-17\eds-binaries\php\php812vs16x64x230619180613\ext
I got:
C:\\**Users04817**\Documents\\___WWW\EasyPHP-Devserver-17\eds-binaries\php\php812vs16x64x230619180613\ext

**To solve my problem, I simply doubled the backslashes**:

# eds-app-actions.php 
```
// UPDATE PHP.INI
$phpini = file_get_contents(__DIR__ . '\\php.ini');
   
    // extension_dir
    $replacement = '${1}' . str_replace('\\', '\\\\', __DIR__) . '\\ext' . '$3';
    $phpini = preg_replace('/^(\s*extension_dir\s*\=\s*\"\s*)(.*)(\".*)$/m', $replacement, $phpini);  

    // zend_extension - xdebug dll
    $replacement = '${1}' . str_replace('\\', '\\\\', __DIR__) . '\\\\' . $php_settings['xdebug_dll'] . '$3';
    $phpini = preg_replace('/^(\s*zend_extension\s*\=\s*\"\s*)(.*)(\".*)$/m', $replacement, $phpini);        
       
file_put_contents (__DIR__ . '\\php.ini', $phpini);
```

This resolved my issue and I wanted to share it with you. I hope it can be helpful.

Regards.

- Florent

**Comment by easyphp** [comment]
Hi. Thanks. It will impemented in the next version.
