### ISSUE TITLE
Getting a NOTICE when I start my xdebug manager 1.7 after I installed php 8.1.1 and Apache server 2.4.48

### ISSUE THREAD

**Issue by Goldenhub** [easyphp/DEVSERVER#290]
I updated my Apache server to 2.4.48 and my php to 8.1.1.
I am getting this error notice when I start my xdebug manager 1.7.

`Notice: Undefined offset: 1 in C:\Program Files (x86)\EasyPHP-Devserver-17\edsmodules\xdebugmanager\xdebugmanager.php on line 20` 
and
`Notice: Undefined offset: 1 in C:\Program Files (x86)\EasyPHP-Devserver-17\edsmodules\xdebugmanager\xdebugmanager.php on line 34`

what do I do please?

**Comment by easyphp** [comment]
Hi. It will fixed with the new version. Xdebug Manager 3.0 will be released in early September.
