### ISSUE TITLE
Can't start any of the services on Windows 10 64bit machine. No error messages.

### ISSUE THREAD

**Issue by abelard3003** [easyphp/DEVSERVER#33]
Hi. I've just installed EasyPHP Devserver 16.1 on a Windows 10 64bit machine and I don't seem to be able to start any of the services - Apache, MYSQL, PHP. Nothing.

I get no error messages and there doesn't seem to be any entries in the relevant error log. On pressing the start button, the browser tab shows the 'busy' indicator for around 15 seconds and the screen greys out, then the screen becomes active again and the start button remains green.

I'm a complete noob, I'm afraid, and I'd be grateful for any advice. Regards. Eric.

![el1](https://cloud.githubusercontent.com/assets/16987157/12702954/6168175a-c82e-11e5-9a8a-a063d905b87a.png)
![el2](https://cloud.githubusercontent.com/assets/16987157/12702955/616af510-c82e-11e5-8fff-8d9ee5fb064c.png)
![el3](https://cloud.githubusercontent.com/assets/16987157/12702956/616b9466-c82e-11e5-90ef-159bdd1f88ae.png)

**Comment by SublymeRick** [comment]
I had this problem, at least with apache becaue I did not have the x86 visual studio 2015 run time package installed. Try installing the run times and see if that helps you.

**Comment by ConnieDaniele** [comment]
I am having this problem as well - I cannot start an HTTP or DB server. I do have Visual C++ Redistributable for Visual Studio 2015 installed. Also on a Windows 10 64-bit machine. Any advice is appreciated.

**Comment by SublymeRick** [comment]
Make sure you have both the x86 and x64 runtimes. I'm not sure which one is required but I know that once I had both of them installed it worked.

**Comment by ConnieDaniele** [comment]
I do have both versions installed :(

I am trying to set-up EasyPHP on two different machines, both running Windows 10 Home 64-bit. Both of these computers already have the x64 AND x86 versions of Visual C++ Redistributable for Visual Studio 2015 PRIOR to install.

Before attempting to install EasyPHP Devserver 16 on either machine, I went ahead and uninstalled all previous versions of EasyPHP for good measure. I even manually deleted all leftover data from Program Files (x86). 

Still, neither machine will start an HTTP or DB server. No errors are produced; the error logs are empty. 

Not that it should matter, but for reference I have tried to run a server using Chrome, Firefox, and IE on BOTH machines. Nothing. 

I'd love to work with Devserver 16, but unfortunately the program doesn't feel the same way about me.

**Comment by SublymeRick** [comment]
:/ Wish I had some other suggestions... Other than contacting the developer on their facebook page you could try posting on the forum but I havent ever had much luck there. I have gotten responses from their facebook though.

**Comment by mcoredev** [comment]
Hi i have same problem with run localhost. One day not working. Anybody resolved this problem?

**Comment by primewaydesign** [comment]
I had exactly same problem.
After looking at the Services (Win 10 x64) it appeared that another MySQL was listed.
That service was blocking the new one..

`SC STOP shortservicename` -> to stop the service
`SC DELETE shortservicename` -> to delete
[This is helpful](http://stackoverflow.com/questions/76074/how-can-i-delete-a-service-in-windows)

After restarting easyPHP 16.1.1 dbserver worked like a charm.

Hope that helps!

**Comment by bgatellier** [comment]
Hi,

Did you check if the ports you're using are not already taken ?
EasyPHP default configuration is to start Apache on port 80. And this port could be already taken by messaging programs like Skype.
Default MySQL port is 3306.
