### ISSUE TITLE
Please disable autorun of xdebug

### ISSUE THREAD

**Issue by StaggerLeee** [easyphp/DEVSERVER#42]
Seems as even if xdebug module is not installed some xdebug functions run in background.
Websites crawl slow, it means those are not less significant functions.

I disabled all xdebug lines in php.ini, and all my websides are now fast as rocket. I cant explain with words what difference it makes.

Feels almost as I came from heavy Drupal website without cache to the one small static HTML website.
On all my websites.

**Comment by easyphp** [comment]
We're gonna check that. Thanks!

**Comment by StaggerLeee** [comment]
Just some feedback. High speed is holding after few days. 
So it is something it should be definitelly looked in.

A bit bizzare situation. Came to the one point in life when I was embarrassed to show clients prototype of websites on my notebook. Ashamed how slow it was.

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @StaggerLeee
