### ISSUE TITLE
Easyphp-devserver Issues

### ISSUE THREAD

**Issue by Prgrmr4Christ** [easyphp/DEVSERVER#49]
When I try connecting to server, despite directory existing and starting server, it says page cannot be displayed. Tried pulling up php file from directory itself (phpinfo.php), and it says open or save. Tried opening, and it re-pulls up the box.

I installed phpmyadmin, but see no way to open it from dashboard.

Is there a way to connect to a website address server as well?

**Comment by easyphp** [comment]
We need more information : message error, screenshot.
About PhpMyAdmin, when you click "open", what happens ?

**Comment by Prgrmr4Christ** [comment]
When I go to phpmyadmin on computer, comes up black box, for about a second which disappears.


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by easyphp** [comment]
Strange. What do you mean by a black box ?
Can you attach a screenshot ?

**Comment by Prgrmr4Christ** [comment]
It's not there long enough. But if you are familiar with cmd.exe, or command prompt, it's a blank version. Tried running as administrator too. Same result.


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------
