### ISSUE TITLE
Feature Request: Customize virtual host manager vhost settings

### ISSUE THREAD

**Issue by RickKukiela** [easyphp/DEVSERVER#51]
I cannot use the virtualhost manager because I need to be able to customize my vhosts a little bit. For example, I use a shared Alias folder on vhosts that use my application on them which is "centrally" installed. I guess there could be a way to set this up globally since it really doesnt matter if hosts that do not need the alias get the alias on my machine but even so, being able to modify the vhosts via virtualhost manager would be a really nice feature.

**Comment by easyphp** [comment]
Now you can. A new version is out : Virtual Hosts Manager 2.0. This version needs Apache 2.4.48.
Download : https://warehouse.easyphp.org

**Comment by RickKukiela** [comment]
A 5 year old issue! nice i will check this out :)
