### ISSUE TITLE
Server not start: Migration DevServer 14.1 VC11 to DevServer 16.1 VC14

### ISSUE THREAD

**Issue by fhfournier** [easyphp/DEVSERVER#59]
Hi, i had before Devserver 14.1 VC11 and now i pay and install Devserver 16.1 VC14.

When i open the dashboard and try to start the server... nothing... No error message, no warning, anything...

I have windows 10 with all the VC i need... When i look in the console (Google Chrome) i can see 2 error 404

GET http://127.0.0.1:1111/library/bootstrap/js/ie-emulation-modes-warning.js 
GET http://127.0.0.1:1111/library/bootstrap/js/ie10-viewport-bug-workaround.js 

Someone can help me please? I have to uninstall and clean in "regedit" or something?

**Comment by easyphp** [comment]
Hi.I don't know where you had to pay for EasyPHP Devserver 16.1 VC14 because EasyPHP Devserver 16.1 VC14 doesn't exist. The last version of EasyPHP Devserver is 16.1.1 and it's free. A usual.

**Comment by fhfournier** [comment]
16.1.1 and i pay for the warehouse but its not the point :-S

**Comment by easyphp** [comment]
- open the Task manager and check if any eds-* process exists. Kill them.
- rerun run-easyphp-devserver.exe
- start the servers
If it doesn't work show us the Apache Error Log.

**Comment by fhfournier** [comment]
I kill any eds-* process and i re-run... And still no log in apache error or access

**Comment by fhfournier** [comment]
Windows path variable environment maybe?

**Comment by easyphp** [comment]
No need to change the path.
Your Error Log file is empty ?
Can you rename your install folder and try to reinstall Devserver 16.1.1 ?

**Comment by fhfournier** [comment]
No i can't change the folder name, said its open in a other program. And yes i try to reinstall more than 30 time (and reboot after each)

**Comment by easyphp** [comment]
Did you install a service ?
Once again, kill all eds-* process, close all files and try again to rename your install folder.
If you still cannot, try to find which application is interfering.
Your problem doesn't seem to be directly related to Devserver.

**Comment by fhfournier** [comment]
all process are kill, i rename the folder installation and still not able to launch apache :( everything work fine if i re-install devserver 14.1 VC11  :S i dont know what wrong

**Comment by rrajendran1956** [comment]
I also faced the same problem. I did the following after which http server and web server are working perfectly.
1. I disabled anti-malware software (malwarebytes) which I loaded recently (in your case it may be antivirus or anti-malware software).It was blocking certain files of phpmyadmin folder
2. Deleted EasyPHP-Devserver-16.1 folder in Prgram files(x86) and shortcut in desktop
3.reinstalled again easyphp dev sever 16.1.1
Best of luck

**Comment by fhfournier** [comment]
I tryed all this... but never work so i format my computer and everything
work now

**Comment by Famous-g** [comment]
Hi,
Got the same problem with Devserver 16.1 freshly downloaded.
I can start server with PHP 5.6.19

- But can't start with PHP 7 :(

I tried all things mentionned here.
VC9, 10, 11, 12 & 14 installed (perhaps too much ? :)

**Comment by Famous-g** [comment]
Precision: I've just got new error message in Apache Error log :
`[mpm_winnt:crit] [pid 6476:tid 328] AH02538: Child: Parent process exited abruptly. Child process is ending`

**Comment by Nemesiss357** [comment]
Hi,

I had the same issue, this is how I fixed my problem:

Software Info:
	* EasyPhp version: 16.1.1
	* Php Version: 7.0.4
	* Apache version : 2.4.18
	* Windows 10 x64
	
	Go to below folder and run the program: "php.exe"
	EasyPHP-Devserver-16.1\eds-binaries\php\php704vc14x86x160717155641
	=> If you have a pop-up window with the error "...VCRUNTIME140.dll is missing ...", it means you are missing a DDL to run PHP 7.
	
	To install the missing DDL, you must download "vc_redist.x86.exe" and install Visual C++ Redistributable for Visual Studio 2015.
	(https://www.microsoft.com/en-us/download/details.aspx?id=48145)
	
	Stop EasyPHP, install the VC package, restart your PC, restart EasyPHP and hopefully it should work.
	
Peace.

**Comment by Olman62** [comment]
I had same problem. Solution: go to the folder C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11 and run unist.exe. After old version uninstalling, new version will run without  problem.
