### ISSUE TITLE
[Feature request] Provide MariaDB builds for Devserver 16.1

### ISSUE THREAD

**Issue by ioleo** [easyphp/DEVSERVER#60]
Please provide MariaDB builds for Devserver 16.1.

**Comment by easyphp** [comment]
We are working on it. It's on our todo list.

**Comment by SublymeRick** [comment]
+1

**Comment by aureltime** [comment]
+1 thanks

**Comment by mikerockett** [comment]
Any updates on this? Also keen.

**Comment by loostro** [comment]
@easyphp Just a suggestion: you should react to feature requests way faster. I had to choose a diffrent solution, as I could not wait more than a few days. Which makes me your ex-customer now.

**Comment by SublymeRick** [comment]
Its september guys!! common with it already!

**Comment by SublymeRick** [comment]
@loostro what did you end up going with?

**Comment by loostro** [comment]
@SublymeRick VirtualBox + Xubuntu (light alternative to Unity) in Seamless mode. Inside the machine I've got docker and all my projects are now dockerized (so my project dependencies are "locked" in the container and don't pollute my Xubuntu guest (or Windows host) systems.

**Comment by mikerockett** [comment]
@loostro - I might want to try this. How big is the total VB + Xubuntu payload?

**Comment by REJack** [comment]
Xubuntu isn't really needed Docker works flawless on Windows 10 too, i'use docker for my testing envoirment.

@mikerockett: A default Xubuntu intallation has round about 1.5 GB+4GB swap drive, VB has 300-400MB, DockerImage based what you use in the docker image, they start from 50MB up to 1GB.

**Comment by loostro** [comment]
@mikerockett My VB machine is 40GB, currently (with all my projects) about 50% of that is free.
@REJack As far as I'm aware Docker on Windows still runs a tiny linux machine on which it install docker. I prefer a fully featured ubuntu instead. I've tried docker on Hyper-V, but its not as performant as in my VirtualBox.

**Comment by REJack** [comment]
@loostro my PHPunit test on a Docker over VM Ubuntu took 30% longer as docker over hyper-v on my laptop (i7-4910MQ, 512GB SSD & 32GB Ram)

**Comment by SublymeRick** [comment]
Everyone, if you're tired of waiting for this feature as I am, I just decided to install MariaDB stand alone. I used mysql work bench to transfer my databases and everything went smooth. The only issue is that EasyPHP dashboard wont display the phpMyAdmin link unless its mysql is started so either you can run it on a local port or bookmark your phpmyadmin page before making the switch, then just access it via bookmarks.

**Comment by mikerockett** [comment]
@SublymeRick - I've also been doing that, but using HeidiSQL instead of phpMyAdmin -- it really is much better.

**Comment by SublymeRick** [comment]
@mikerockett thanks for the heads up, I'm checking it out now.
