### ISSUE TITLE
MySql Front Connection Error

### ISSUE THREAD

**Issue by Virusoft** [easyphp/DEVSERVER#65]
Hi every body, firstly thanks for your helps,
I have a problem when connecting with MySql Front 2.5 or 5 or HeidiSQL_9.3;
## I cant connect to MySql database,

error code is: 
MySql-Error;
Connection failed:
## 1043: Bad handshake.

thanks alot of.
![front_error](https://cloud.githubusercontent.com/assets/18748355/14934315/dd76ff82-0eb5-11e6-8143-595451c39934.jpg)

**Comment by CyrilCharlier** [comment]
Hi,

witth a fist install of Mysql-front 5.3 (last version on the site), no problem : 

![2016-04-30_08h59_45](https://cloud.githubusercontent.com/assets/11455745/14934493/e6cf7158-0eb1-11e6-90ba-24a8f49ecf23.png)

can't reproduce this to help you.

**Comment by CyrilCharlier** [comment]
Alert like this : 
![2016-04-30_13h09_13](https://cloud.githubusercontent.com/assets/11455745/14935520/e84552e6-0ed4-11e6-95f2-8e7f875ffce6.png)

**Comment by Virusoft** [comment]
yes, thanks.
this is it.

2016-04-30 14:10 GMT+03:00, CyrilCharlier <notifications@github.com>:
> Alert like this :
> ![2016-04-30_13h09_13](https://cloud.githubusercontent.com/assets/11455745/14935520/e84552e6-0ed4-11e6-95f2-8e7f875ffce6.png)
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/easyphp/easyphp-devserver/issues/65#issuecomment-215955861


-- 
-----------------------------------------------------------
Mustafa SAYIN
Bilgisayar-Elektrik-Elektronik Teknisyeni.
www.ViruSoft.com
0543 343 59 73

**Comment by Virusoft** [comment]
really; MySQL Front 2.5 too stabil and basic, I want use it but for this time using 5.3,
thanks for helps,

**Comment by CyrilCharlier** [comment]
I tried to do a mysql_upgrade to create those tables but :

C:\EasyPHP-Devserver-16.1\eds-binaries\dbserver\mysql5711x86x160409113218\bin>mysql_upgrade.exe
**Error occurred: Cannot setup server variables.**

@easyphp could you try to loot at this ?

**Comment by CyrilCharlier** [comment]
I tried this : 
`mysqld --skip-grant-tables`
and after to do this :
`mysql_upgrade`

but `mysql: [ERROR] unknown option '--skip-grant-tables'`

**Comment by CyrilCharlier** [comment]
When i turn on database mysql in phpmyadmin and i want to see the table 'innodb_index_stats' : 
![2016-04-30_14h06_12](https://cloud.githubusercontent.com/assets/11455745/14935771/d89f72a6-0edc-11e6-8347-d7c956031a16.png)
